def default_pricing_rules():
    return {
        'currency': 'CLP',
        'minimumGuestCount': 10,
        'visibleMaximumGuestCount': 60,
        'firstTierMaximumGuestCount': 15,
        'secondTierMaximumGuestCount': 30,
        'firstTierBasePrice': 200000,
        'secondTierBasePrice': 230000,
        'extraGuestPrice': 5000,
        'baseSchedule': {
            'start': '09:00',
            'end': '18:00',
        },
        'additionalHourPrice': 20000,
        'maximumAdditionalHours': 3,
        'depositRate': 0.5,
        'simulatorMicrocopy': '',
    }


def default_experience_cards():
    return [
        {
            'title': 'Piscina',
            'description': 'Piscina amplia para refrescarse y disfrutar durante toda la jornada.',
            'icon': 'pool',
        },
        {
            'title': 'Quincho exterior',
            'description': 'Espacio techado para comidas, pausas y organizacion del encuentro.',
            'icon': 'table',
        },
        {
            'title': 'Areas verdes',
            'description': 'Jardines amplios para circular, descansar y compartir al aire libre.',
            'icon': 'leaf',
        },
        {
            'title': 'Parrillas',
            'description': 'Parrillas disponibles para asados, comidas y encuentros al aire libre.',
            'icon': 'grill',
        },
        {
            'title': 'Mesa de ping pong',
            'description': 'Mesa disponible para partidas recreativas durante el evento.',
            'icon': 'game',
        },
        {
            'title': 'Taca taca',
            'description': 'Juego clasico para sumar entretencion y dinamica grupal.',
            'icon': 'game',
        },
        {
            'title': 'Cama elastica',
            'description': 'Espacio pensado para diversion infantil y energia al aire libre.',
            'icon': 'spark',
        },
        {
            'title': 'Duchas',
            'description': 'Duchas disponibles para mayor comodidad durante la estadia.',
            'icon': 'shower',
        },
        {
            'title': 'Cocina',
            'description': 'Area de apoyo para preparar, organizar y servir alimentos.',
            'icon': 'kitchen',
        },
        {
            'title': 'Microondas',
            'description': 'Microondas habilitado para calentar y apoyar el servicio.',
            'icon': 'microwave',
        },
        {
            'title': 'Hervidor',
            'description': 'Hervidor disponible para bebidas calientes y apoyo de cocina.',
            'icon': 'kettle',
        },
        {
            'title': 'Refrigeradores',
            'description': 'Espacio de refrigeracion para bebidas, alimentos y abastecimiento.',
            'icon': 'fridge',
        },
        {
            'title': 'Cancha futbol',
            'description': 'Cancha habilitada para pichangas y actividad deportiva grupal.',
            'icon': 'sport',
        },
        {
            'title': 'Cancha voleibol',
            'description': 'Espacio disponible para partidos recreativos de voleibol.',
            'icon': 'volleyball',
        },
        {
            'title': 'Estacionamiento',
            'description': 'Llegada comoda para invitados y vehiculos sin tension operativa.',
            'icon': 'car',
        },
        {
            'title': 'Apoyo operativo',
            'description': 'Infraestructura de respaldo para ordenar mejor la jornada o evento.',
            'icon': 'support',
        },
    ]


def default_gallery_images():
    return [
        {
            'id': 'piscina-principal',
            'src': '/images/parcela/piscina-principal.jpg',
            'alt': 'Piscina principal de la parcela rodeada de jardines y arboles.',
            'label': 'Piscina principal',
            'caption': 'Piscina amplia con jardines, reposeras y espacios para descansar durante la jornada.',
            'area': 'Agua y descanso',
            'objectPosition': 'center 58%',
            'orientation': 'landscape',
        },
        {
            'id': 'terraza-vista-piscina',
            'src': '/images/parcela/terraza-vista-piscina.jpg',
            'alt': 'Terraza exterior con sombrillas, mesas y vista hacia la piscina.',
            'label': 'Terraza exterior',
            'caption': 'Zona exterior con mesas, sombra y circulacion directa hacia las areas verdes.',
            'area': 'Encuentro',
            'objectPosition': 'center center',
            'orientation': 'landscape',
        },
        {
            'id': 'quincho-comedor',
            'src': '/images/parcela/quincho-comedor.jpg',
            'alt': 'Quincho techado con mesas, sillas y vista al jardin.',
            'label': 'Quincho techado',
            'caption': 'Espacio techado para comidas, celebraciones y apoyo operativo del evento.',
            'area': 'Comedor exterior',
            'objectPosition': 'center 46%',
            'orientation': 'landscape',
        },
        {
            'id': 'jardin-trampolin',
            'src': '/images/parcela/jardin-trampolin.jpg',
            'alt': 'Jardin amplio con trampolin, piscina al fondo y vista a la montana.',
            'label': 'Jardin amplio',
            'caption': 'Jardines amplios para compartir, jugar y moverse con comodidad.',
            'area': 'Aire libre',
            'objectPosition': 'center center',
            'orientation': 'landscape',
        },
        {
            'id': 'cancha-palmeras',
            'src': '/images/parcela/cancha-palmeras.jpg',
            'alt': 'Cancha de pasto enmarcada por palmeras y cierre perimetral.',
            'label': 'Cancha',
            'caption': 'Area deportiva y recreativa para actividades durante el arriendo.',
            'area': 'Actividad',
            'objectPosition': 'center 54%',
            'orientation': 'landscape',
        },
        {
            'id': 'piscina-atardecer',
            'src': '/images/parcela/piscina-atardecer.jpg',
            'alt': 'Piscina iluminada al atardecer con montana de fondo.',
            'label': 'Piscina al atardecer',
            'caption': 'Un ambiente mas calido para mostrar la parcela cuando baja la luz.',
            'area': 'Atardecer',
            'objectPosition': 'center 44%',
            'orientation': 'landscape',
        },
        {
            'id': 'piscina-camastros',
            'src': '/images/parcela/piscina-camastros.jpg',
            'alt': 'Piscina con camastros blancos y sombra lateral.',
            'label': 'Reposeras',
            'caption': 'Zona de descanso junto a la piscina para pausas y conversacion.',
            'area': 'Relax',
            'objectPosition': 'center 52%',
            'orientation': 'landscape',
        },
        {
            'id': 'piscina-jardin',
            'src': '/images/parcela/piscina-jardin.jpg',
            'alt': 'Piscina junto a jardin amplio y arboles.',
            'label': 'Piscina y jardin',
            'caption': 'Vista abierta de piscina y areas verdes para dimensionar el espacio.',
            'area': 'Agua y jardin',
            'objectPosition': 'center center',
            'orientation': 'landscape',
        },
        {
            'id': 'piscina-reposeras',
            'src': '/images/parcela/piscina-reposeras.jpg',
            'alt': 'Piscina con reposeras bajo estructura de sombra.',
            'label': 'Piscina con sombra',
            'caption': 'Reposeras y sombra para disfrutar la jornada con comodidad.',
            'area': 'Descanso',
            'objectPosition': 'center 46%',
            'orientation': 'landscape',
        },
        {
            'id': 'terraza-sombrillas',
            'src': '/images/parcela/terraza-sombrillas.jpg',
            'alt': 'Terraza con mesas, sillas y sombrillas.',
            'label': 'Sombrillas',
            'caption': 'Terraza equipada con mesas y sombrillas para grupos.',
            'area': 'Terraza',
            'objectPosition': 'center 48%',
            'orientation': 'landscape',
        },
        {
            'id': 'terraza-jardin',
            'src': '/images/parcela/terraza-jardin.jpg',
            'alt': 'Mesa de terraza con vista al jardin.',
            'label': 'Terraza jardin',
            'caption': 'Un rincon exterior para conversar mirando las areas verdes.',
            'area': 'Vista verde',
            'objectPosition': 'center 45%',
            'orientation': 'landscape',
        },
        {
            'id': 'quincho-mesa-interior',
            'src': '/images/parcela/quincho-mesa-interior.jpg',
            'alt': 'Mesa larga dentro del quincho techado.',
            'label': 'Mesa interior',
            'caption': 'Mesa de apoyo para almuerzos, celebraciones y preparacion.',
            'area': 'Quincho',
            'objectPosition': 'center 50%',
            'orientation': 'square',
        },
        {
            'id': 'fachada-quincho-jardin',
            'src': '/images/parcela/fachada-quincho-jardin.jpg',
            'alt': 'Fachada del quincho junto a jardin y arboles.',
            'label': 'Fachada quincho',
            'caption': 'Vista exterior del quincho y su relacion con el jardin.',
            'area': 'Infraestructura',
            'objectPosition': 'center center',
            'orientation': 'landscape',
        },
        {
            'id': 'cabana-jardin',
            'src': '/images/parcela/cabana-jardin.jpg',
            'alt': 'Construccion roja rodeada de arbustos y jardin.',
            'label': 'Cabana y jardin',
            'caption': 'Volumen construido rodeado de vegetacion y sombra natural.',
            'area': 'Entorno',
            'objectPosition': 'center 42%',
            'orientation': 'square',
        },
        {
            'id': 'jardin-arboles',
            'src': '/images/parcela/jardin-arboles.jpg',
            'alt': 'Jardin con arboles y sendero de pasto.',
            'label': 'Jardin arbolado',
            'caption': 'Vegetacion abundante que aporta privacidad y sensacion de descanso.',
            'area': 'Naturaleza',
            'objectPosition': 'center center',
            'orientation': 'landscape',
        },
        {
            'id': 'jardin-lateral',
            'src': '/images/parcela/jardin-lateral.jpg',
            'alt': 'Jardin lateral con sol y construcciones a los costados.',
            'label': 'Jardin lateral',
            'caption': 'Areas verdes laterales para circulacion y actividades tranquilas.',
            'area': 'Aire libre',
            'objectPosition': 'center center',
            'orientation': 'square',
        },
        {
            'id': 'cancha-nublada',
            'src': '/images/parcela/cancha-nublada.jpg',
            'alt': 'Cancha de pasto con arcos, malla y sendero lateral.',
            'label': 'Cancha amplia',
            'caption': 'Espacio deportivo para actividades recreativas y juegos grupales.',
            'area': 'Deporte',
            'objectPosition': 'center 54%',
            'orientation': 'landscape',
        },
        {
            'id': 'acceso-palmeras',
            'src': '/images/parcela/acceso-palmeras.jpg',
            'alt': 'Acceso exterior con palmeras y porton.',
            'label': 'Acceso con palmeras',
            'caption': 'Ingreso exterior con vegetacion y amplitud visual.',
            'area': 'Acceso',
            'objectPosition': 'center center',
            'orientation': 'square',
        },
        {
            'id': 'acceso-palmeras-cancha',
            'src': '/images/parcela/acceso-palmeras-cancha.jpg',
            'alt': 'Acceso con palmeras y vista hacia cancha de pasto.',
            'label': 'Acceso a cancha',
            'caption': 'Ingreso hacia la zona deportiva y areas abiertas.',
            'area': 'Entrada',
            'objectPosition': 'center 50%',
            'orientation': 'landscape',
        },
        {
            'id': 'estacionamiento-amplio',
            'src': '/images/parcela/estacionamiento-amplio.jpg',
            'alt': 'Estacionamiento amplio con varios vehiculos.',
            'label': 'Estacionamiento',
            'caption': 'Zona exterior para recibir vehiculos de los invitados.',
            'area': 'Llegada',
            'objectPosition': 'center 44%',
            'orientation': 'square',
        },
        {
            'id': 'estacionamiento-montana',
            'src': '/images/parcela/estacionamiento-montana.jpg',
            'alt': 'Estacionamiento con palmeras y vista a la montana.',
            'label': 'Vista de llegada',
            'caption': 'Llegada amplia con vegetacion y vista al entorno natural.',
            'area': 'Llegada',
            'objectPosition': 'center 46%',
            'orientation': 'landscape',
        },
    ]


def default_hero_gallery_image_ids():
    return [
        'piscina-principal',
        'terraza-vista-piscina',
        'quincho-comedor',
        'jardin-trampolin',
        'piscina-atardecer',
        'cancha-palmeras',
    ]


def default_location_map():
    return {
        'venue': {
            'name': 'Parcela recreativa',
            'address': '',
            'latitude': None,
            'longitude': None,
            'mapImageUrl': '',
            'mapNotes': '',
        },
        'points': [],
    }
