# Generated by Django 6.0.4 on 2026-04-13 00:48

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('guest_count', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('observed', 'Observada'), ('awaiting_payment', 'En espera de pago'), ('payment_submitted', 'Comprobante enviado'), ('confirmed', 'Confirmada'), ('rejected', 'Rechazada'), ('cancelled', 'Cancelada'), ('expired', 'Expirada')], default='pending', max_length=30)),
                ('quoted_total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='CLP', max_length=3)),
                ('customer_message', models.TextField(blank=True)),
                ('internal_notes', models.TextField(blank=True)),
                ('status_reason', models.TextField(blank=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('status_updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ReservationStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_status', models.CharField(blank=True, choices=[('pending', 'Pendiente'), ('observed', 'Observada'), ('awaiting_payment', 'En espera de pago'), ('payment_submitted', 'Comprobante enviado'), ('confirmed', 'Confirmada'), ('rejected', 'Rechazada'), ('cancelled', 'Cancelada'), ('expired', 'Expirada')], max_length=30)),
                ('to_status', models.CharField(choices=[('pending', 'Pendiente'), ('observed', 'Observada'), ('awaiting_payment', 'En espera de pago'), ('payment_submitted', 'Comprobante enviado'), ('confirmed', 'Confirmada'), ('rejected', 'Rechazada'), ('cancelled', 'Cancelada'), ('expired', 'Expirada')], max_length=30)),
                ('comment', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation_status_changes', to=settings.AUTH_USER_MODEL)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='reservations.reservation')),
            ],
            options={
                'verbose_name': 'Reservation status history',
                'verbose_name_plural': 'Reservation status history',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['status', 'start_date', 'end_date'], name='reservation_status_c8ada4_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['customer', 'status'], name='reservation_custome_e440be_idx'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='reservations_reservation_valid_range'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.CheckConstraint(condition=models.Q(('guest_count__gte', 1)), name='reservations_reservation_guest_count_positive'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.CheckConstraint(condition=models.Q(('quoted_total_amount__gt', Decimal('0.00')), ('quoted_total_amount__isnull', True), _connector='OR'), name='reservations_reservation_positive_quote_if_present'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('status__in', ('pending', 'observed', 'awaiting_payment', 'payment_submitted', 'confirmed'))), expressions=[(models.Func(models.F('start_date'), models.F('end_date'), models.Value('[]'), function='daterange', output_field=django.contrib.postgres.fields.ranges.DateRangeField()), '&&')], name='reservations_no_overlapping_active_reservations'),
        ),
        migrations.AddIndex(
            model_name='reservationstatushistory',
            index=models.Index(fields=['reservation', 'created_at'], name='reservation_reserva_096bb6_idx'),
        ),
        migrations.AddIndex(
            model_name='reservationstatushistory',
            index=models.Index(fields=['to_status', 'created_at'], name='reservation_to_stat_9a2db7_idx'),
        ),
    ]
