# Generated by Django 6.0.4 on 2026-04-13 00:48

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialDatePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('daily_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='CLP', max_length=3)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Special date price',
                'verbose_name_plural': 'Special date prices',
                'ordering': ('start_date', 'end_date'),
                'indexes': [models.Index(fields=['is_active', 'start_date', 'end_date'], name='pricing_spe_is_acti_7d9ee7_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='pricing_special_date_price_valid_range'), models.CheckConstraint(condition=models.Q(('daily_price__gt', Decimal('0.00'))), name='pricing_special_date_price_positive_amount'), django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('is_active', True)), expressions=[(models.Func(models.F('start_date'), models.F('end_date'), models.Value('[]'), function='daterange', output_field=django.contrib.postgres.fields.ranges.DateRangeField()), '&&')], name='pricing_special_date_price_no_overlap_when_active')],
            },
        ),
    ]
