# Generated by Django 6.0.4 on 2026-04-13 00:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('block_type', models.CharField(choices=[('maintenance', 'Mantenimiento'), ('owner_use', 'Uso interno'), ('event', 'Evento privado'), ('other', 'Otro')], default='maintenance', max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_blocked_dates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blocked date',
                'verbose_name_plural': 'Blocked dates',
                'ordering': ('start_date', 'end_date'),
                'indexes': [models.Index(fields=['is_active', 'start_date', 'end_date'], name='availabilit_is_acti_638264_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='availability_blocked_date_valid_range')],
            },
        ),
    ]
