# Generated by Django 6.0.4 on 2026-04-13 00:48

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='payment-receipts/%Y/%m/')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='CLP', max_length=3)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('reference_number', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('review_status', models.CharField(choices=[('pending_review', 'Pendiente de revision'), ('approved', 'Aprobado'), ('rejected', 'Rechazado')], default='pending_review', max_length=20)),
                ('review_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_receipts', to='reservations.reservation')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_payment_receipts', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_payment_receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment receipt',
                'verbose_name_plural': 'Payment receipts',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['reservation', 'review_status'], name='payments_pa_reserva_6eb6df_idx'), models.Index(fields=['review_status', 'created_at'], name='payments_pa_review__c20b18_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', Decimal('0.00')), ('amount__isnull', True), _connector='OR'), name='payments_payment_receipt_positive_amount_if_present')],
            },
        ),
    ]
