# Generated by Django 6.0.4 on 2026-04-13 13:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('reservations', '0002_alter_reservation_status_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='paymentreceipt',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('review_status', 'pending_review'), ('reviewed_by__isnull', True), ('reviewed_at__isnull', True)), models.Q(('review_status__in', ('approved', 'rejected')), ('reviewed_by__isnull', False), ('reviewed_at__isnull', False)), _connector='OR'), name='payments_payment_receipt_review_fields_consistent'),
        ),
    ]
