# Generated by Django 6.0.4 on 2026-04-13 14:02

import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('short_description', models.TextField(blank=True)),
                ('location_name', models.CharField(blank=True, max_length=150)),
                ('address', models.TextField(blank=True)),
                ('max_guest_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('base_daily_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='CLP', max_length=3)),
                ('check_in_time', models.TimeField(blank=True, null=True)),
                ('check_out_time', models.TimeField(blank=True, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('amenities', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Property info',
                'verbose_name_plural': 'Property info',
                'ordering': ('-is_active', '-updated_at'),
                'constraints': [models.CheckConstraint(condition=models.Q(('base_daily_price__gt', Decimal('0.00')), ('base_daily_price__isnull', True), _connector='OR'), name='properties_property_info_positive_base_daily_price_if_present'), models.CheckConstraint(condition=models.Q(('max_guest_count__gte', 1), ('max_guest_count__isnull', True), _connector='OR'), name='properties_property_info_positive_max_guest_count_if_present'), models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='properties_property_info_single_active_record')],
            },
        ),
    ]
